"""criar tabela logs_atividade

Revision ID: 14a3371a69ff
Revises: ee1f246aed51
Create Date: 2026-09-11 22:29:05.712727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a3371a69ff'
down_revision: Union[str, Sequence[str], None] = 'ee1f246aed51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_atividade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.Enum('CRIAR', 'EDITAR', 'EXCLUIR', 'LOGIN', 'LOGIN_FALHOU', name='tipoacao'), nullable=False),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=True),
    sa.Column('detalhes', sa.String(length=500), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_atividade')
    # ### end Alembic commands ###
