"""criar tabela documentos

Revision ID: a38f4c3eabad
Revises: 14a3371a69ff
Create Date: 2026-09-23 21:14:04.968805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38f4c3eabad'
down_revision: Union[str, Sequence[str], None] = '14a3371a69ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('CAR', 'LICENCA_AMBIENTAL', 'LAUDO_TECNICO', 'OUTRO', name='tipodocumento'), nullable=False),
    sa.Column('entidade_tipo', sa.Enum('FAZENDA', 'TALHAO', name='entidadedocumento'), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('enviado_por_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enviado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    # ### end Alembic commands ###
