"""criar tabelas core: produtor, fazenda, talhao, safra, cultura, colheita, lote

Revision ID: ee1f246aed51
Revises: 8526e4394282
Create Date: 2026-09-11 22:04:40.589084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'ee1f246aed51'
down_revision: Union[str, Sequence[str], None] = '8526e4394282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('culturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_lote', sa.String(length=50), nullable=False),
    sa.Column('peso_total_kg', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_lote')
    )
    op.create_table('produtores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtores_cpf_cnpj'), 'produtores', ['cpf_cnpj'], unique=True)
    op.create_table('safras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identificacao', sa.String(length=30), nullable=False),
    sa.Column('ano_inicio', sa.Integer(), nullable=False),
    sa.Column('ano_fim', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacao')
    )
    op.create_table('fazendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('area_total_hectares', sa.Float(), nullable=True),
    sa.Column('localizacao', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('produtor_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talhoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_identificador', sa.String(length=100), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('poligono', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('fazenda_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fazenda_id'], ['fazendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talhao_safra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talhao_id', sa.UUID(), nullable=False),
    sa.Column('safra_id', sa.UUID(), nullable=False),
    sa.Column('cultura_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cultura_id'], ['culturas.id'], ),
    sa.ForeignKeyConstraint(['safra_id'], ['safras.id'], ),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colheitas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('localizacao_coleta', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('data_colheita', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantidade_kg', sa.Float(), nullable=False),
    sa.Column('talhao_safra_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['talhao_safra_id'], ['talhao_safra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_colheita',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('colheita_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['colheita_id'], ['colheitas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lote_colheita')
    op.drop_table('colheitas')
    op.drop_table('talhao_safra')
    op.drop_table('talhoes')
    op.drop_table('fazendas')
    op.drop_table('safras')
    op.drop_index(op.f('ix_produtores_cpf_cnpj'), table_name='produtores')
    op.drop_table('produtores')
    op.drop_table('lotes')
    op.drop_table('culturas')
    # ### end Alembic commands ###
